/**
 * LA BIBLIOTHÈQUE D'ÉMOJIS DU SÉLECTEUR — toutes catégories, avec
 * recherche
 * ==================================================================
 * Chaque entrée : [émoji, mots-clés de recherche] — les mots-clés en
 * français, sans accents (la recherche retire les accents des deux
 * côtés). Aucune dépendance : une liste choisie à la main, assez
 * large pour une bio, organisée comme les claviers d'aujourd'hui.
 */

export type EntreeEmoji = readonly [string, string];

export const CATEGORIES_EMOJIS: ReadonlyArray<{
  slug: string;
  titre: string;
  emojis: ReadonlyArray<EntreeEmoji>;
}> = [
  {
    slug: "visages",
    titre: "Visages",
    emojis: [
      ["😀", "sourire content heureux"],
      ["😃", "sourire grand joie"],
      ["😄", "rire joie yeux"],
      ["😁", "sourire dents"],
      ["😆", "rire fou"],
      ["😅", "rire sueur ouf"],
      ["🤣", "mort de rire"],
      ["😂", "larmes de rire"],
      ["🙂", "petit sourire"],
      ["😉", "clin oeil"],
      ["😊", "sourire timide doux"],
      ["😇", "ange auréole"],
      ["🥰", "amoureux coeurs"],
      ["😍", "yeux coeur amour"],
      ["🤩", "etoiles impressionne"],
      ["😘", "bisou coeur"],
      ["😗", "bisou"],
      ["😎", "lunettes cool"],
      ["🤓", "intello lunettes"],
      ["🧐", "monocle inspecte"],
      ["🤔", "reflechit pense"],
      ["🤗", "calin bras ouverts"],
      ["🤭", "oups main bouche"],
      ["🤫", "chut silence secret"],
      ["😏", "sourire en coin malin"],
      ["😌", "soulage serein"],
      ["😴", "dort sommeil"],
      ["🥱", "baille fatigue"],
      ["😷", "masque malade"],
      ["🤒", "fievre thermometre"],
      ["🥳", "fete anniversaire cotillons"],
      ["😤", "determination souffle"],
      ["😢", "triste larme"],
      ["😭", "pleure sanglots"],
      ["😱", "peur cri choc"],
      ["😳", "gene rougit surpris"],
      ["🥺", "supplie yeux doux"],
      ["😬", "grimace aie"],
      ["🙄", "yeux au ciel blase"],
      ["😐", "neutre bof"],
      ["🤯", "explose tete choque"],
      ["😈", "diablotin malicieux"],
      ["🤡", "clown"],
      ["👻", "fantome halloween"],
      ["💀", "crane squelette skull tete de mort"],
      ["☠️", "tete de mort pirate danger"],
      ["👽", "extraterrestre alien"],
      ["🤖", "robot machine"],
    ],
  },
  {
    slug: "gestes",
    titre: "Gestes & personnes",
    emojis: [
      ["👋", "salut coucou main"],
      ["🤚", "main levee stop"],
      ["✋", "main stop cinq"],
      ["🖖", "salut vulcain"],
      ["👌", "ok parfait"],
      ["🤌", "doigts pinces italien"],
      ["✌️", "victoire paix deux"],
      ["🤞", "doigts croises chance"],
      ["🤟", "je t aime signe"],
      ["🤘", "rock metal cornes"],
      ["🤙", "appelle moi cool"],
      ["👈", "doigt gauche"],
      ["👉", "doigt droite"],
      ["👆", "doigt haut"],
      ["👇", "doigt bas"],
      ["☝️", "index haut un"],
      ["👍", "pouce haut super oui"],
      ["👎", "pouce bas non"],
      ["✊", "poing leve force"],
      ["👊", "poing coup check"],
      ["🤛", "poing gauche"],
      ["🤜", "poing droite"],
      ["👏", "applaudit bravo"],
      ["🙌", "mains levees hourra"],
      ["🫶", "coeur mains amour"],
      ["👐", "mains ouvertes"],
      ["🤲", "paumes ouvertes offrande"],
      ["🤝", "poignee de main accord"],
      ["🙏", "merci priere svp"],
      ["✍️", "ecrit main stylo"],
      ["💪", "muscle force biceps"],
      ["🦾", "bras mecanique force"],
      ["🖤", "coeur noir dark"],
      ["👁️", "oeil regard"],
      ["👀", "yeux regarde"],
      ["🧠", "cerveau idee"],
      ["🦴", "os squelette"],
      ["👤", "silhouette profil"],
      ["🧑‍🎨", "artiste peintre"],
      ["💃", "danse flamenco"],
      ["🕺", "danse disco"],
      ["🧘", "meditation yoga zen"],
    ],
  },
  {
    slug: "animaux",
    titre: "Animaux & nature",
    emojis: [
      ["🐍", "serpent snake"],
      ["🐉", "dragon"],
      ["🐲", "dragon tete"],
      ["🦅", "aigle rapace"],
      ["🦉", "hibou chouette nuit"],
      ["🐺", "loup wolf"],
      ["🦊", "renard"],
      ["🐗", "sanglier"],
      ["🐅", "tigre felin"],
      ["🐆", "leopard panthere"],
      ["🦁", "lion felin roi"],
      ["🐘", "elephant"],
      ["🦋", "papillon butterfly"],
      ["🐛", "chenille insecte"],
      ["🐝", "abeille miel"],
      ["🕷️", "araignee spider"],
      ["🕸️", "toile araignee"],
      ["🦂", "scorpion"],
      ["🐢", "tortue"],
      ["🐙", "pieuvre poulpe tentacule"],
      ["🦑", "calamar"],
      ["🦈", "requin shark"],
      ["🐋", "baleine mer"],
      ["🐬", "dauphin mer"],
      ["🐠", "poisson tropical"],
      ["🎏", "carpe koi drapeau"],
      ["🐦‍⬛", "corbeau oiseau noir"],
      ["🕊️", "colombe paix oiseau"],
      ["🦇", "chauve souris bat nuit"],
      ["🐈‍⬛", "chat noir"],
      ["🐱", "chat mignon"],
      ["🐶", "chien"],
      ["🦌", "cerf bois"],
      ["🐴", "cheval"],
      ["🦄", "licorne"],
      ["🌹", "rose fleur epines"],
      ["🥀", "rose fanee fleur"],
      ["🌸", "fleur cerisier sakura"],
      ["🌺", "hibiscus fleur"],
      ["🌻", "tournesol fleur"],
      ["🌼", "marguerite fleur"],
      ["🪷", "lotus fleur zen"],
      ["🌿", "feuilles branche nature"],
      ["🍃", "feuille vent nature"],
      ["🍂", "feuilles automne"],
      ["🌵", "cactus desert"],
      ["🌲", "sapin foret arbre"],
      ["🌳", "arbre feuillu"],
      ["🍄", "champignon"],
      ["🌙", "lune croissant nuit"],
      ["🌕", "pleine lune"],
      ["⭐", "etoile star"],
      ["🌟", "etoile brillante"],
      ["✨", "etincelles paillettes"],
      ["⚡", "eclair foudre"],
      ["🔥", "feu flamme fire"],
      ["🌊", "vague mer ocean"],
      ["💧", "goutte eau"],
      ["❄️", "flocon neige hiver"],
      ["☀️", "soleil"],
      ["🌈", "arc en ciel"],
      ["🌪️", "tornade vent"],
      ["🪐", "planete saturne espace"],
      ["🌍", "terre monde planete"],
    ],
  },
  {
    slug: "nourriture",
    titre: "Nourriture & boissons",
    emojis: [
      ["🍒", "cerises fruit"],
      ["🍓", "fraise fruit"],
      ["🍑", "peche fruit"],
      ["🍎", "pomme rouge"],
      ["🍋", "citron"],
      ["🍉", "pasteque"],
      ["🍇", "raisin"],
      ["🥑", "avocat"],
      ["🌶️", "piment epice"],
      ["🍕", "pizza"],
      ["🍔", "burger"],
      ["🌮", "taco mexique"],
      ["🍣", "sushi japon"],
      ["🍜", "ramen nouilles"],
      ["🍙", "onigiri riz"],
      ["🍡", "dango brochette"],
      ["🥟", "ravioli gyoza"],
      ["🍦", "glace"],
      ["🍩", "donut"],
      ["🍪", "cookie biscuit"],
      ["🎂", "gateau anniversaire"],
      ["🍫", "chocolat"],
      ["🍬", "bonbon"],
      ["☕", "cafe tasse"],
      ["🍵", "the matcha"],
      ["🧋", "bubble tea"],
      ["🍺", "biere"],
      ["🍻", "bieres trinquer sante"],
      ["🍷", "vin verre"],
      ["🍸", "cocktail martini"],
      ["🍹", "cocktail tropical"],
      ["🥂", "champagne trinquer"],
      ["🥃", "whisky verre"],
      ["🧉", "mate"],
      ["🥤", "soda gobelet"],
      ["🧊", "glacon"],
      ["💧", "goutte eau"],
      ["🍌", "banane fruit"],
      ["🍍", "ananas fruit"],
      ["🥥", "noix de coco"],
      ["🥝", "kiwi fruit"],
      ["🍊", "orange mandarine"],
      ["🍅", "tomate"],
      ["🌽", "mais epi"],
      ["🥕", "carotte"],
      ["🍄", "champignon"],
      ["🥐", "croissant"],
      ["🥖", "baguette pain"],
      ["🧀", "fromage"],
      ["🍟", "frites"],
      ["🌭", "hot dog"],
      ["🥗", "salade"],
      ["🍝", "pates spaghetti"],
      ["🍤", "crevette tempura"],
      ["🦐", "crevette"],
      ["🍯", "miel pot"],
      ["🧁", "cupcake"],
      ["🍭", "sucette"],
      ["🍿", "popcorn"],
      ["🥠", "biscuit chinois"],
    ],
  },
  {
    slug: "activites",
    titre: "Activités & sport",
    emojis: [
      ["⚽", "foot ballon"],
      ["🏀", "basket ballon"],
      ["🏈", "football americain"],
      ["🎾", "tennis balle"],
      ["🏐", "volley"],
      ["🎱", "billard huit"],
      ["🏓", "ping pong"],
      ["🥊", "boxe gant"],
      ["🥋", "judo karate kimono"],
      ["⛷️", "ski neige"],
      ["🏄", "surf vague"],
      ["🏊", "natation nage"],
      ["🚴", "velo cyclisme"],
      ["🧗", "escalade grimpe"],
      ["🏋️", "musculation halteres"],
      ["🤸", "gym acrobatie"],
      ["🛹", "skate planche"],
      ["🎿", "skis"],
      ["🏆", "trophee coupe victoire"],
      ["🥇", "medaille or premier"],
      ["🎯", "cible flechettes precis"],
      ["🎮", "manette jeux video gaming"],
      ["🕹️", "joystick arcade"],
      ["🎲", "de jeu hasard"],
      ["♟️", "echecs pion"],
      ["🃏", "joker carte"],
      ["🀄", "mahjong dragon rouge"],
      ["🎴", "cartes fleurs hanafuda"],
      ["🎪", "cirque chapiteau"],
      ["🎭", "theatre masques comedie"],
      ["🎨", "palette peinture art"],
      ["🎬", "clap cinema film"],
      ["🎤", "micro chant"],
      ["🎧", "casque musique"],
      ["🎼", "partition musique"],
      ["🎵", "note musique"],
      ["🎶", "notes musique"],
      ["🎸", "guitare rock"],
      ["🎹", "piano clavier"],
      ["🥁", "batterie tambour"],
      ["🎺", "trompette"],
      ["🎻", "violon"],
    ],
  },
  {
    slug: "voyages",
    titre: "Voyages & lieux",
    emojis: [
      ["🗼", "tour tokyo paris"],
      ["🗽", "statue liberte new york"],
      ["🗾", "carte japon"],
      ["🏯", "chateau japonais"],
      ["🏰", "chateau fort"],
      ["⛩️", "torii sanctuaire japon"],
      ["🗻", "mont fuji montagne"],
      ["🏔️", "montagne neige sommet"],
      ["🌋", "volcan eruption"],
      ["🏝️", "ile deserte palmier"],
      ["🏖️", "plage parasol"],
      ["🏜️", "desert dunes"],
      ["🌃", "ville nuit"],
      ["🌆", "ville crepuscule"],
      ["🌉", "pont nuit"],
      ["🎡", "grande roue fete"],
      ["🎢", "montagnes russes"],
      ["⛺", "tente camping"],
      ["🚗", "voiture"],
      ["🏍️", "moto"],
      ["🚲", "velo"],
      ["🚂", "train locomotive"],
      ["✈️", "avion voyage"],
      ["🚀", "fusee espace"],
      ["🛸", "ovni soucoupe"],
      ["⛵", "voilier bateau"],
      ["🚢", "navire paquebot"],
      ["⚓", "ancre marin mer"],
      ["🧭", "boussole direction"],
      ["🗺️", "carte monde voyage"],
      ["🌍", "terre monde europe afrique"],
      ["🌎", "terre monde ameriques"],
      ["🌏", "terre monde asie"],
      ["🏙️", "gratte ciel ville"],
      ["🌌", "voie lactee nuit etoiles"],
      ["🏞️", "parc nature riviere"],
      ["🏕️", "camping nature"],
      ["🌅", "lever de soleil"],
      ["🌄", "soleil montagnes"],
      ["🗿", "moai statue"],
      ["🛖", "hutte cabane"],
      ["🚇", "metro"],
      ["🚕", "taxi"],
      ["🛵", "scooter"],
      ["🚐", "van fourgon"],
      ["🛻", "pick up camionnette"],
      ["🧳", "valise bagage"],
      ["🎫", "billet ticket"],
      ["🛎️", "sonnette hotel"],
    ],
  },
  {
    slug: "objets",
    titre: "Objets",
    emojis: [
      ["⌚", "montre heure"],
      ["📱", "telephone portable"],
      ["💻", "ordinateur portable"],
      ["📷", "appareil photo"],
      ["📸", "photo flash"],
      ["🎥", "camera film"],
      ["🔍", "loupe recherche"],
      ["💡", "ampoule idee"],
      ["🔦", "lampe torche"],
      ["🕯️", "bougie flamme"],
      ["🪔", "lampe huile"],
      ["📚", "livres lecture"],
      ["📖", "livre ouvert"],
      ["✏️", "crayon dessin"],
      ["🖋️", "stylo plume encre"],
      ["🖊️", "stylo bille"],
      ["🖌️", "pinceau peinture"],
      ["🖍️", "craie pastel"],
      ["📌", "punaise epingle"],
      ["📍", "epingle lieu adresse"],
      ["✂️", "ciseaux couper"],
      ["🗡️", "dague epee couteau"],
      ["⚔️", "epees croisees combat"],
      ["🛡️", "bouclier protection"],
      ["🔪", "couteau lame"],
      ["🪒", "rasoir lame"],
      ["💉", "seringue aiguille encre tatouage"],
      ["🩸", "goutte sang"],
      ["💊", "pilule medicament"],
      ["🧲", "aimant"],
      ["🔗", "chaine lien maillon"],
      ["⛓️", "chaines metal"],
      ["🧨", "dynamite explosif"],
      ["🔨", "marteau outil"],
      ["🛠️", "outils marteau cle"],
      ["⚙️", "engrenage mecanique"],
      ["⚗️", "alambic alchimie"],
      ["🔮", "boule cristal magie"],
      ["🧿", "oeil bleu nazar protection"],
      ["📿", "chapelet perles"],
      ["💎", "diamant pierre precieuse"],
      ["👑", "couronne roi reine"],
      ["💍", "bague anneau"],
      ["🕶️", "lunettes soleil"],
      ["🎩", "chapeau haut de forme"],
      ["🧢", "casquette"],
      ["👟", "basket chaussure"],
      ["🥀", "rose fanee"],
      ["⏳", "sablier temps"],
      ["🕰️", "horloge ancienne temps"],
      ["🔔", "cloche sonnette"],
      ["🎁", "cadeau paquet"],
      ["🎈", "ballon fete"],
      ["🎉", "cotillons fete bravo"],
      ["🏮", "lanterne rouge japon"],
      ["🪞", "miroir reflet"],
      ["🧵", "fil couture"],
      ["🪡", "aiguille couture"],
    ],
  },
  {
    slug: "symboles",
    titre: "Symboles & cœurs",
    emojis: [
      ["🖤", "coeur noir dark"],
      ["❤️", "coeur rouge amour"],
      ["🤍", "coeur blanc"],
      ["💜", "coeur violet"],
      ["💙", "coeur bleu"],
      ["💚", "coeur vert"],
      ["💛", "coeur jaune"],
      ["🧡", "coeur orange"],
      ["🤎", "coeur marron"],
      ["❤️‍🔥", "coeur en feu passion"],
      ["💔", "coeur brise chagrin"],
      ["💕", "deux coeurs"],
      ["💞", "coeurs qui tournent"],
      ["💫", "etoile filante vertige"],
      ["💥", "explosion boum"],
      ["💯", "cent pour cent parfait"],
      ["♠️", "pique carte"],
      ["♥️", "coeur carte"],
      ["♦️", "carreau carte"],
      ["♣️", "trefle carte"],
      ["☯️", "yin yang equilibre"],
      ["☮️", "paix peace"],
      ["✝️", "croix chretienne"],
      ["☪️", "croissant etoile"],
      ["🕉️", "om hindou"],
      ["♾️", "infini toujours"],
      ["⚜️", "fleur de lys"],
      ["🔱", "trident neptune"],
      ["⚕️", "caducee medecine"],
      ["⚛️", "atome science"],
      ["✡️", "etoile david"],
      ["🔺", "triangle rouge"],
      ["🔻", "triangle bas"],
      ["⭕", "cercle rond"],
      ["❌", "croix non"],
      ["❗", "exclamation attention"],
      ["❓", "question"],
      ["➕", "plus ajouter"],
      ["➖", "moins"],
      ["✔️", "coche valide"],
      ["☢️", "radioactif danger"],
      ["☣️", "biohazard danger"],
      ["⚠️", "attention danger triangle"],
      ["🚫", "interdit"],
      ["🔞", "moins dix huit interdit mineurs"],
      ["🆗", "ok bouton"],
      ["🆕", "nouveau new"],
    ],
  },
  {
    slug: "drapeaux",
    titre: "Drapeaux",
    emojis: [
      // LES DRAPEAUX GÉNÉRIQUES d'abord — ils ne désignent pas un pays.
      ["🏳️", "drapeau blanc"],
      ["🏴", "drapeau noir"],
      ["🏁", "drapeau damier course"],
      ["🚩", "drapeau rouge"],
      ["🎌", "drapeaux croises japon"],
      ["🏳️‍🌈", "drapeau arc en ciel fierte lgbt"],
      ["🏳️‍⚧️", "drapeau trans transgenre"],
      ["🏴‍☠️", "drapeau pirate tete de mort"],
      // PUIS LES PAYS. Le site est mondial : la liste couvre l'Europe
      // entière, les Amériques, l'Asie, l'Afrique et l'Océanie — un
      // tatoueur doit trouver SON pays, et celui de ses conventions.
      // (Ordre : francophonie et voisins d'abord, puis par continent.)
      ["🇫🇷", "france francais drapeau"],
      ["🇧🇪", "belgique belge drapeau"],
      ["🇨🇭", "suisse drapeau"],
      ["🇱🇺", "luxembourg drapeau"],
      ["🇲🇨", "monaco drapeau"],
      ["🇨🇦", "canada canadien quebec drapeau"],
      // Europe
      ["🇪🇸", "espagne espagnol drapeau"],
      ["🇵🇹", "portugal portugais drapeau"],
      ["🇮🇹", "italie italien drapeau"],
      ["🇩🇪", "allemagne allemand drapeau"],
      ["🇦🇹", "autriche drapeau"],
      ["🇳🇱", "pays bas hollande drapeau"],
      ["🇬🇧", "royaume uni angleterre britannique drapeau"],
      ["🇮🇪", "irlande irlandais drapeau"],
      ["🇩🇰", "danemark drapeau"],
      ["🇸🇪", "suede suedois drapeau"],
      ["🇳🇴", "norvege norvegien drapeau"],
      ["🇫🇮", "finlande finlandais drapeau"],
      ["🇮🇸", "islande drapeau"],
      ["🇵🇱", "pologne polonais drapeau"],
      ["🇨🇿", "tcheque tchequie republique drapeau"],
      ["🇸🇰", "slovaquie drapeau"],
      ["🇭🇺", "hongrie hongrois drapeau"],
      ["🇷🇴", "roumanie roumain drapeau"],
      ["🇧🇬", "bulgarie drapeau"],
      ["🇬🇷", "grece grec drapeau"],
      ["🇭🇷", "croatie drapeau"],
      ["🇷🇸", "serbie drapeau"],
      ["🇸🇮", "slovenie drapeau"],
      ["🇧🇦", "bosnie herzegovine drapeau"],
      ["🇦🇱", "albanie drapeau"],
      ["🇺🇦", "ukraine ukrainien drapeau"],
      ["🇱🇹", "lituanie drapeau"],
      ["🇱🇻", "lettonie drapeau"],
      ["🇪🇪", "estonie drapeau"],
      ["🇲🇹", "malte drapeau"],
      ["🇨🇾", "chypre drapeau"],
      ["🇹🇷", "turquie turc drapeau"],
      ["🇷🇺", "russie russe drapeau"],
      ["🇪🇺", "europe union europeenne drapeau"],
      // Amériques
      ["🇺🇸", "etats unis americain usa drapeau"],
      ["🇲🇽", "mexique mexicain chicano drapeau"],
      ["🇧🇷", "bresil bresilien drapeau"],
      ["🇦🇷", "argentine argentin drapeau"],
      ["🇨🇱", "chili chilien drapeau"],
      ["🇨🇴", "colombie colombien drapeau"],
      ["🇵🇪", "perou peruvien drapeau"],
      ["🇺🇾", "uruguay drapeau"],
      ["🇻🇪", "venezuela drapeau"],
      ["🇨🇺", "cuba cubain drapeau"],
      ["🇩🇴", "republique dominicaine drapeau"],
      ["🇭🇹", "haiti haitien drapeau"],
      // Asie
      ["🇯🇵", "japon japonais irezumi drapeau"],
      ["🇰🇷", "coree du sud coreen drapeau"],
      ["🇨🇳", "chine chinois drapeau"],
      ["🇹🇼", "taiwan drapeau"],
      ["🇹🇭", "thailande thai drapeau"],
      ["🇻🇳", "vietnam vietnamien drapeau"],
      ["🇮🇩", "indonesie bali drapeau"],
      ["🇵🇭", "philippines filipino drapeau"],
      ["🇮🇳", "inde indien drapeau"],
      ["🇵🇰", "pakistan drapeau"],
      ["🇮🇱", "israel drapeau"],
      ["🇱🇧", "liban libanais drapeau"],
      ["🇦🇪", "emirats arabes unis dubai drapeau"],
      // Afrique
      ["🇲🇦", "maroc marocain drapeau"],
      ["🇩🇿", "algerie algerien drapeau"],
      ["🇹🇳", "tunisie tunisien drapeau"],
      ["🇪🇬", "egypte egyptien drapeau"],
      ["🇸🇳", "senegal senegalais drapeau"],
      ["🇨🇮", "cote d ivoire ivoirien drapeau"],
      ["🇨🇲", "cameroun camerounais drapeau"],
      ["🇲🇱", "mali malien drapeau"],
      ["🇨🇩", "congo rdc drapeau"],
      ["🇳🇬", "nigeria nigerian drapeau"],
      ["🇬🇭", "ghana drapeau"],
      ["🇰🇪", "kenya drapeau"],
      ["🇿🇦", "afrique du sud drapeau"],
      ["🇲🇬", "madagascar malgache drapeau"],
      // Océanie
      ["🇦🇺", "australie australien drapeau"],
      ["🇳🇿", "nouvelle zelande maori drapeau"],
      ["🇵🇫", "polynesie tahiti drapeau"],
      ["🇳🇨", "nouvelle caledonie drapeau"],
    ],
  },
];

/** Retire les accents pour une recherche indulgente. */
export function sansAccents(texte: string): string {
  return texte.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
}

/** Les émojis dont les mots-clés contiennent la recherche. */
export function chercherEmojis(recherche: string): EntreeEmoji[] {
  const propre = sansAccents(recherche.trim());
  if (!propre) return [];
  const resultats: EntreeEmoji[] = [];
  for (const categorie of CATEGORIES_EMOJIS) {
    for (const entree of categorie.emojis) {
      if (sansAccents(entree[1]).includes(propre)) resultats.push(entree);
    }
  }
  return resultats.slice(0, 64);
}
